#!/bin/bash
# 
# 
#
#  run this script to create selectbox.json
# 
#  ./mkstn > selectbox.json
# 
#head -1 LST/fd*/datumTable_???.html | cut -d\> -f 4 | cut -d\< -f1 | sed -e '/^$/d' -e 's/_/\ /' -e 's/_/,\ /' > bar2
head -1 TIDES_DATUMS/fd/LST/fd*/datumTable_???_m.html | cut -d\> -f 4 | cut -d\< -f1 | sed -e '/^$/d' -e 's/_/\ /' -e 's/_/,\ /' > bar2

cat << '_EOF1'
{
  "results": [
_EOF1

while read LINE; do
  stnid=`echo $LINE | cut -c 1-3`
  name=`echo $LINE | cut -c 5-`
  printf '     {\n      "id": "'
  echo -n $stnid
  printf '",\n      "text": "'
  echo -n $LINE
  printf '"\n     },\n'
  #printf "      <option value=\"$pid\">$pid $name</option>\n"
done < bar2

cat << '_EOF2'
 ],
  "pagination": {
    "more": true
  }
}
_EOF2

rm bar2

